name: Sphinx Docs

on: [push, pull_request]

jobs:
  build:
    name: "Build and Deploy"
    runs-on: macos-latest
    env:
      CXX: clang++
      BUILD_CONFIG: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH='/usr/local/opt/boost'
        -DSEQUANT_BUILD_DOCS=ON
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          brew install ninja boost catch2
          brew install --cask doxygen
          pip install -r doc/sphinx/requirements.txt

      - name: Build Docs
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_CONFIG
          cmake --build . --target sphinx-sequant

      - name: Deploy to gh-pages
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        if: ${{ github.event_name == 'push'}}
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/build/doc/sphinx/html
